import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import HomePage from "../components/Home/HomePage";
import WorksSection from "../components/Works/WorksSection";
import Marqueex from "../components/Marquee/Marquee";
import Header from './../components/Header/Header';
import Slider from '../components/Slider/Slider';
import Footer from '../components/Footer/Footer';
import Logo from './../components/Logo/Logo';
import { useRef, useState,useEffect } from "react"; 
import dynamic from 'next/dynamic';
import { useRecoilState } from 'recoil';
import { LoaderState } from './../atoms/LoaderAtom';
import Preloader from '../components/Preloader/Preloader';
import { AnimatePresence } from 'framer-motion';

const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
  ssr: false

});

export default function Home() {
  const [loading,setLoading] = useRecoilState(LoaderState)

   useEffect(() => {
    if (typeof window === "undefined" || loading) return;
    let scroll;
    import("locomotive-scroll").then((locomotiveModule) => {
  scroll = new locomotiveModule.default({
        el:document.querySelector("[data-scroll-container]"),
        smooth: true,
        smoothMobile: false,
        resetNativeScroll: true,
      });
    });

    return () => scroll.destroy();
  });


  useEffect(()=>{
  setTimeout(()=>{
    setLoading(false)
  },10000)
},[]);







  return (
    <div  data-scroll-container 
    className="bg-[#EEF0F2] target z-0">
      <Head>
        <title>Hazem Wahb - Junior Front-end Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       {loading && (<Preloader/>)}

      <AnimatedCursor
      innerSize={15}
      outerSize={8}
      color='0,0,0'
      outerAlpha={0.4}
      innerScale={0.7}
      outerScale={8}
      clickables={[
        'a',
        "li",
        ".content__item",
        'input[type="text"]',
        'input[type="email"]',
        'input[type="number"]',
        'input[type="submit"]',
        'input[type="image"]',
        'label[for]',
        'select',
        'textarea',
        'button',
        '.link',
        ".menu-item-container",
        ".getintouch-circle-footer",
        ".project-item ",
      ]}
      />
      {!loading && <HomePage/>}
     {!loading && <Marqueex/>}
      {!loading && <Slider/>}
     {!loading && <Footer/>}

       {/* <WorksSection/> */}

    </div>
  )
}
